# Generated by Django 2.2.16 on 2022-05-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220517_1008"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user have moderator admin",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_moderator",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user have moderator status",
                verbose_name="moderator status",
            ),
        ),
    ]
