# Generated by Django 2.2.16 on 2022-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_auto_20220512_1544"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="gerne",
        ),
        migrations.AddField(
            model_name="title",
            name="gerne",
            field=models.ManyToManyField(
                related_name="titles", to="reviews.Genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="unique_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(
                fields=("name", "slug"), name="unique_genre"
            ),
        ),
    ]
