# Generated by Django 2.2.16 on 2022-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_auto_20220515_1914"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
