# Generated by Django 2.2.16 on 2022-05-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_title_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenreTitle",
        ),
    ]
